server:
  port: ${AUTH_SERVICE_PORT:8081}

spring:
  application:
    name: auth-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
