export const SPACE_PERMISSIONS = {
  SPACE_READ: 'space:read',
  SPACE_MANAGE: 'space:manage',
  SPACE_DELETE: 'space:delete',
  MEMBER_READ: 'member:read',
  MEMBER_MANAGE: 'member:manage',
  ROLE_READ: 'role:read',
  ROLE_MANAGE: 'role:manage',
  DOCUMENT_READ: 'document:read',
  DOCUMENT_CREATE: 'document:create',
  DOCUMENT_EDIT: 'document:edit',
  AGENT_READ: 'agent:read',
  AGENT_MANAGE: 'agent:manage',
  AGENT_BIND_SKILL: 'agent:bind_skill',
  AGENT_BIND_MCP: 'agent:bind_mcp',
  SKILL_READ: 'skill:read',
  SKILL_MANAGE: 'skill:manage',
  MCP_READ: 'mcp:read',
  MCP_MANAGE: 'mcp:manage',
  TASK_READ: 'task:read',
  TASK_CREATE: 'task:create',
  TASK_TERMINATE: 'task:terminate',
  CHANGE_REQUEST_READ: 'change_request:read',
  CHANGE_REQUEST_SUBMIT: 'change_request:submit',
  CHANGE_REQUEST_APPROVE: 'change_request:approve',
  CHANGE_REQUEST_MERGE: 'change_request:merge',
  USAGE_READ: 'usage:read',
  AUDIT_READ: 'audit:read',
} as const

export type SpacePermissionCode = (typeof SPACE_PERMISSIONS)[keyof typeof SPACE_PERMISSIONS]
